# this file needs to be modified to match list of 'ALPINETAG's in the Jenkins matrix

# e.g 'FROM ghcr.io/imagegenius/aports-cache:v<ALPINETAG>-<arch> as v<ALPINETAG>-<arch>'
FROM ghcr.io/imagegenius/aports-cache:v3.17-x86_64 as v3.17-x86_64
FROM ghcr.io/imagegenius/aports-cache:v3.17-aarch64 as v3.17-aarch64

FROM scratch

# e.g 'COPY --from=v<ALPINETAG>-<arch> / /'
COPY --from=v3.17-x86_64 / /
COPY --from=v3.17-aarch64 / /
